### ISSUE TITLE
License of the contract

### ISSUE THREAD

**Issue by ScJa** [christianlundkvist/simple-multisig#10]
Hi,

I would like to use an adaption of your contract for a research project, would you be ok with licensing it (e.g. MIT license)?

Thanks,
Jakob

**Comment by christianlundkvist** [comment]
Hi Jakob! Sure, I can MIT license it, no problem! May I ask what the research project is?

**Comment by VoR0220** [comment]
I too am looking to slightly modify this so that instead of sending funds it's assigning roles. It's very well designed.

**Comment by christianlundkvist** [comment]
@VoR0220 note that it can currently send any possible Ethereum transaction except creating contracts (not just sending funds), so you may be able to do what you want with the contract as-is.

**Comment by VoR0220** [comment]
@christianlundkvist That's the thing ;) I want to be able to create contracts with this

**Comment by christianlundkvist** [comment]
@VoR0220 Ah got it!

**Comment by ScJa** [comment]
@christianlundkvist My master thesis covers how to safely hold cryptocurrency funds as a business. I will also propose possible implementations. 
I would extend your smart contract so it would be able to support different owner-weights (e.g. the CEO would count as two signatures).

**Comment by VoR0220** [comment]
also the ability to just switch a user is nice. I'm assuming that someone is going to lose a private key somewhere and they should be able to replace it somehow.

**Comment by VoR0220** [comment]
@ScJa That's a damn good suggestion, but again, the title is "simple-multisig"...I think it's meant to be extended.

**Comment by christianlundkvist** [comment]
@ScJa @VoR0220  Note that the goal was to make the contract as simple as possible which is why it doesn’t have the advanced features of replacing owners, added weights etc. Note that having the CEO count as two signatures could probably be done client side by having the CEO use two keys (potentially hidden by a UI).

In any case I added an MIT licence in this commit: https://github.com/christianlundkvist/simple-multisig/commit/15a8095818008b0bf3eb901e488d0c5b488513d4

**Comment by ScJa** [comment]
Thanks Christian,
I wasn't suggesting for you to add this feature, I'm aware it is a "luxury". I was only trying to give you information about what I plan to adapt.
