### ISSUE TITLE
Unable to pre-sign transactions with web3.eth.sign

### ISSUE THREAD

**Issue by christoph2806** [christianlundkvist/simple-multisig#12]
https://github.com/christianlundkvist/simple-multisig/blob/71136f4d9c8c1352ceefaf96dd2ed480b8e5fb60/test/simplemultisig.js#L3

Currently, it's not possible to presign transactions with `web3.eth.sign` because you can't pass a hex string to the signing function.

Or any ideas how to to so?

**Comment by christianlundkvist** [comment]
web3 purposefully disabled the ability to sign arbitrary hashes because they were worried that people would be tricked into signing transactions. Thus web3 prepends a string `\x19Ethereum signed message` or something like this. I thought personally this was a bit silly because it will just lead to people creating multisigs and other high value contracts that require this exact string to be passed in.

To answer your question you have to use a tool like lightwallet or other signing tool to sign the data.

**Comment by christoph2806** [comment]
Which shows that the web3 approach is a bit questionable, because malicious developers won't be stopped by this.
