### ISSUE TITLE
Race to nonce update problem

### ISSUE THREAD

**Issue by elenadimitrova** [christianlundkvist/simple-multisig#21]
In a scenario where there are multiple messages being collected signatures for there is a race condition to update the nonce. Logically the simplest sequence is as follows:

- `nonce = 0`, derive message hash `X` and start collecting signatures off chain
- `nonce = 0`, derive message hash `Y` and start collecting signatures off chain
- collect signatures for `X` and execute successfully => `nonce` updated to `1`
- collect signatures for `Y` and execute => fails

**Comment by christianlundkvist** [comment]
@elenadimitrova I'm afraid I don't understand what the problem is, can you elaborate? Note that all signatures should be on the same message.

**Comment by christianlundkvist** [comment]
@elenadimitrova Ok I think I see what you are saying: We want to send 100 ETH to address `0xaaaa` so we start collecting signatures for that, and we also want to send 500 ETH to address `0xbbbb` so we collect signatures for that (also with nonce 0). Then yes, once we've sent 100 ETH to address `0xaaaa` we cannot execute the transaction that sends 100 ETH to `0xbbbb`.

The solution is simply to be aware of upcoming transactions, i.e. since we know that we have an upcoming payment to `0xaaaa` we would use nonce 1 instead of nonce 0 when collecting the signatures for the payment to `0xbbbb`.

**Comment by elenadimitrova** [comment]
Thanks @christianlundkvist I understand the "solution" but this implies strict order of upcoming transactions, i.e. sequential model of execution, 1-at-a-time. I've tried to circumnavigate past that by extending the concept of nonce. Will post here if anything reusable come out of it.
